apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
  namespace: application
plugin: jwt
config:
  key_claim_name: kid
  claims_to_verify:
    - exp
  secret_is_base64: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-prometheus
  namespace: application
config:
  minute: 10 
  policy: local
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus-plugin
  namespace: kong
config:

plugin: prometheus
