apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: kong-client-jwt
  namespace: default
consumerRef: kong-client
type: jwt
config:
  key: kong-client-id      
  secretRef:
    name: jwt-secret  
    key: jwt-secret             
  algorithm: HS256
