apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false" 
    keyvaultName: user-app-kv
    objects: |
      array:
        - |
          objectName: "auth-db-url"
          objectType: "secret"
        - |
          objectName: "notif-db-url"
          objectType: "secret"
        - |
          objectName: "jwt-secret-key"
          objectType: "secret"
        - |
          objectName: "asb-connection-string"
          objectType: "secret"
        - |
          objectName: "mailersend-api-key"
          objectType: "secret"
    tenantId: dbd6664d-4eb9-46eb-99d8-5c43ba153c61
