apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-srv
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-srv
  template:
    metadata:
      labels:
        app: auth-srv
    spec:
      containers:
      - name: auth-srv
        image: docker.io/eydarouaz/auth-srv:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: auth-db-url
              key: auth-db-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret-key
              key: jwt-secret-key
        - name: AZURE_SERVICE_BUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: asb-connection-string
              key: asb-connection-string
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-keyvault-secrets"
          nodePublishSecretRef:
            name: secrets-store-creds
